import type { Metadata } from 'next'
import { League_Spartan } from 'next/font/google'
import './globals.css'
import LayoutMain from '@/sections/layoutMain'

const league_spartan = League_Spartan(
  {
  subsets:['latin'],
  weight: ['100','200','300','400','500','600','700','800','900'],
  variable:'--font-spartan'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${league_spartan.variable} font-sans`}>
      <body>
        <LayoutMain>     
        <div>{children}</div>
        </LayoutMain>
      </body>
    </html>
  )
}
